name: Fetch and Save GitHub Repository Data

on:
  push:
    branches:
      - main

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      
      - name: Set Up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Remove Old Data
        run: |
          rm data.json
      
      - name: Fetch Data Using GitHub API
        run: |
          # 'REPOS' must be on the format 'OWNER/REPOSITORY'
          REPOS=(
            "FabricioDosSantosMoreira/react-web-calculator"
            "FabricioDosSantosMoreira/DIO.me"
          )

          # Inicia um arquivo JSON vazio
          echo "[" > data.json

          # Itera sobre os repositórios e busca dados
          for REPO in "${REPOS[@]}"; do
            OWNER=$(echo "$REPO" | cut -d '/' -f 1)
            NAME=$(echo "$REPO" | cut -d '/' -f 2)

            echo "Buscando dados de $REPO..."

            RESPONSE=$(curl -X POST -H "Authorization: Bearer $READ_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"query\": \"{ repository(owner: \\\"$OWNER\\\", name: \\\"$NAME\\\") { name owner { login } openGraphImageUrl } }\"}" \
              https://api.github.com/graphql)

            # Adiciona os dados ao arquivo JSON
            echo "$RESPONSE" | jq '.data.repository' >> data.json
            echo "," >> data.json # Adiciona uma vírgula para separar os objetos
          done

          # Remove a última vírgula e fecha o array JSON
          sed -i '$ s/,$//' data.json
          echo "]" >> data.json

      - name: Commit and Push Data
        run: |
          git add data.json
          git commit -m "[UPDATE] - data.json"
          git push
