name: Fetch and Save GitHub Repository Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      
      - name: Set Up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local pull.rebase true
      
      - name: Remove Old Data And Commit
        run: |
          rm -f data.json
          
          _date=$(TZ="UTC" date +"%d/%m/%Y %H:%M") 

          git add .
          git commit --allow-empty -m "[REMOVE] - data.json ($_date)"

      - name: Fetch Repository Data Using GitHub API
        env:
          READ_ACCESS_TOKEN: ${{ secrets.READ_ACCESS_TOKEN }}
        run: |
          # 'REPOS' must be on the format 'OWNER/REPOSITORY'
          REPOS=(
            "FabricioDosSantosMoreira/react-web-calculator"
            "FabricioDosSantosMoreira/DIO.me"
            "FabricioDosSantosMoreira/PlanetsVsGalaxiesClassifier"
            "FabricioDosSantosMoreira/LeetCode-Solutions"
            "FabricioDosSantosMoreira/TicTacToe"
            "FabricioDosSantosMoreira/SENAI-projeto-django"
            "FabricioDosSantosMoreira/XPe-Python-Bootcamp"
            "FabricioDosSantosMoreira/PyQT5-Basic-Examples"
          )

          # Open 'data.json' with a '['
          echo "[" > data.json

          # Iterate over 'REPOS' to search data
          for REPO in "${REPOS[@]}"; do
            OWNER=$(echo "$REPO" | cut -d '/' -f 1)
            NAME=$(echo "$REPO" | cut -d '/' -f 2)

            echo "Fetching Data | $REPO"

            RESPONSE=$(curl -X POST -H "Authorization: Bearer $READ_ACCESS_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"query\": \"{ repository(owner: \\\"$OWNER\\\", name: \\\"$NAME\\\") { name description url openGraphImageUrl languages(first: 100) { edges { node { name } size } } } }\"}" \
              https://api.github.com/graphql
            )

            echo "Data Fetched | $RESPONSE"

            # Adds 'RESPONSE' to 'data.json'
            echo "$RESPONSE" | jq '.data.repository' >> data.json
            
            # Adds a ',' to 'data.json' to separate objects
            echo "," >> data.json
          done
          
          # Removes the last ','
          sed -i '$ s/,$//' data.json

          # Closes 'data.json' with a ']'
          echo "]" >> data.json

      - name: Fetch And Commit Color Data Using CURL
        env:
          READ_ACCESS_TOKEN: ${{ secrets.READ_ACCESS_TOKEN }}
        run: |
          echo "Downloading GitHub Colors JSON..."
          
          # -f, --fail, Fail silently (no output at all) on HTTP errors.
          # -o, --output, Write output to 'colors.json' instead of stdout
          if curl -f -o colors.json https://raw.githubusercontent.com/ozh/github-colors/master/colors; then
            _date=$(TZ="UTC" date +"%d/%m/%Y %H:%M")
            git add colors.json
            git commit --allow-empty -m "[UPDATE] - colors.json ($_date)"
          fi




      - name: Commit and Push Data
        run: |
          _date=$(TZ="UTC" date +"%d/%m/%Y %H:%M")
          
          git add data.json
          git commit --allow-empty -m "[UPDATE] - data.json ($_date)"

          git pull
          git push
