name: Fetch and Save Repository Data

on:
  push:
    branches:
      - main

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch Data from GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.READ_ACCESS_TOKEN }}
        run: |
          # Defina a lista de repositórios no formato "owner/repo"
          REPOS=(
            'FabricioDosSantosMoreira/react-web-calculator'
            'FabricioDosSantosMoreira/DIO.me'
            'FabricioDosSantosMoreira/TicTacToe'
            'FabricioDosSantosMoreira/SENAI-projeto-django'
            'FabricioDosSantosMoreira/XPe-Python-Bootcamp'
            'FabricioDosSantosMoreira/PyQT5-Basic-Examples'
            'FabricioDosSantosMoreira/PlanetsVsGalaxiesClassifier'
            'FabricioDosSantosMoreira/LeetCode-Solutions'
          )

          # Inicia um arquivo JSON vazio
          echo "[" > repo_data.json

          # Itera sobre os repositórios e busca dados
          for REPO in "${REPOS[@]}"; do
            OWNER=$(echo "$REPO" | cut -d '/' -f 1)
            NAME=$(echo "$REPO" | cut -d '/' -f 2)

            echo "Buscando dados de $REPO..."

            RESPONSE=$(curl -X POST -H "Authorization: Bearer $READ_ACCESS_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"query\": \"{ repository(owner: \\\"$OWNER\\\", name: \\\"$NAME\\\") { name owner { login } openGraphImageUrl } }\"}" \
              https://api.github.com/graphql)

            # Adiciona os dados ao arquivo JSON
            echo "$RESPONSE" | jq '.data.repository' >> repo_data.json
            echo "," >> repo_data.json # Adiciona uma vírgula para separar os objetos
          done

          # Remove a última vírgula e fecha o array JSON
          sed -i '$ s/,$//' repo_data.json
          echo "]" >> repo_data.json

      - name: Commit and Push Data
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add repo_data.json
          git commit -m "[UPDATE] - Fetch Data"
          git push
